[package]
name = "algom"
version = "0.1.0"
authors = ["Miskatul Anwar, miskatul.anwar.csecu@gmail.com"]
edition = "2021"
license = "MIT OR Apache-2.0"
[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[[bin]]
name = "a_quicksort"
path = "src/a_quicksort.rs"

